@startmindmap

*[#orange] **Transaction**
++ computed by (interpreting) **a** [[https://specs.anoma.net/v0.1.4/arch/system/state/resource_machine/data_structures/transaction/transaction_function.html#transaction-function transaction function]]
+++_ needs to be run by the executor
+++_ transaction function calculation on the [[https://specs.anoma.net/v0.1.4/arch/system/state/resource_machine/primitive_interfaces/transaction_function_vm.html transaction function ᴠᴍ]]
+++_ produces ""transaction"" as a result
++ some kind of //"code"//
+++[#white] **TODO** specifically/examples?

-- verification\n(via proving systems)
---_ compute ""verify"" operation
---_ check gas
---_ [[https://specs.anoma.net/v0.1.4/arch/system/state/resource_machine/primitive_interfaces/transaction_function_vm.html → Transaction function ᴠᴍ]]
-- //"execution"//\n
--- perform reads an writes
---- transaction function computation
---- transaction //"execution"//
---[#white] **TODO** other side effects ???


/' if we had a "parallel" mindmap //here//
 ' *[#green] c
 ' ++ b
 ' -- a
 '/
@endmindmap
